name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Cache linuxbrew
        id: cache-linuxbrew
        uses: actions/cache@v2
        with:
          path: ~/.linuxbrew
          key: ${{ runner.os }}-linuxbrew
      - name: Cache pyenv
        id: cache-pyenv
        uses: actions/cache@v2
        with:
          path: ~/.pyenv
          key: ${{ runner.os }}-pyenv
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv
      - name: Install environment dependencies
        run: |
          sudo apt-get install openssl1.0-dev libcurl-openssl1.0-dev libcurl3
      - name: Install Python 2.7.12
        if: steps.cache-pyenv.outputs.cache-hit != 'true'
        env:
          PYTHON_CONFIGURE_OPTS: --enable-unicode=ucs2
        run: |
          curl https://pyenv.run | bash
          ~/.pyenv/bin/pyenv install 2.7.12
          ~/.pyenv/bin/pyenv local 2.7.12
      - name: Install virtualenv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          ~/.pyenv/shims/pip install virtualenv
          ~/.pyenv/shims/virtualenv venv --python $(pyenv which python)
      - name: Setup dependencies
        run: |
          source venv/bin/activate
          which pip
          pip install -r requirements.txt -r requirements_dev.txt
#      - name: Test
#        run: |
#          source venv/bin/activate
#          python -m unittest discover -s src -t src -p *_test.py
      - name: Build
        run: |
          source venv/bin/activate
          which python
          python build.py
#      - name: Lint with flake8
#        run: |
#          source Virtualenv/bin/activate
#          export SRC=Contents/Code
#          flake8 $SRC --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 $SRC --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Test with pytest
#        run: |
#          source Virtualenv/bin/activate
#          export PYTHONPATH=Contents/Code
#          pytest --cov-config=.coveragerc --cov-report=xml --cov=$PYTHONPATH $PYTHONPATH/test
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage.xml
#          flags: unittests
#          name: codecov-umbrella
#          fail_ci_if_error: true
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: outputs/*.tar.gz

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Cache pyenv
        id: cache-pyenv
        uses: actions/cache@v2
        with:
          path: ~/.pyenv
          key: ${{ runner.os }}-pyenv
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv
      - name: Install Python 2.7.17
        if: steps.cache-pyenv.outputs.cache-hit != 'true'
        run: |
          brew install pyenv
          pyenv install 2.7.17
          pyenv local 2.7.17
      - name: Install virtualenv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          ~/.pyenv/shims/pip install virtualenv
          ~/.pyenv/shims/virtualenv venv --python $(pyenv which python)
      - name: Setup dependencies
        run: |
          export XCODE_DEVELOPER=$(xcode-select -p)
          export MACOS_SDK=$XCODE_DEVELOPER/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          export X11=$MACOS_SDK/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11
          ln -s $X11 /usr/local/include/X11
          source venv/bin/activate
          pip install -r requirements.txt -r requirements_dev.txt
#      - name: Test
#        run: |
#          source venv/bin/activate
#          python -m unittest discover -s src -t src -p *_test.py
      - name: Build
        run: |
          source venv/bin/activate
          which python
          python build.py
#      - name: Lint with flake8
#        run: |
#          source Virtualenv/bin/activate
#          export SRC=Contents/Code
#          flake8 $SRC --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 $SRC --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Test with pytest
#        run: |
#          source Virtualenv/bin/activate
#          export PYTHONPATH=Contents/Code
#          pytest --cov-config=.coveragerc --cov-report=xml --cov=$PYTHONPATH $PYTHONPATH/test
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage.xml
#          flags: unittests
#          name: codecov-umbrella
#          fail_ci_if_error: true
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: outputs/*.tar.gz
