name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Setup environments
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Install dependencies
        run: |
          sudo apt-get install libjpeg-dev
          virtualenv Virtualenv
          source Virtualenv/bin/activate
          pip install -r Requirements.txt
          git apply ImageFilePatch.diff
      - name: Lint with flake8
        run: |
          export SRC=Contents/Code
          flake8 $SRC --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 $SRC --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export PYTHONPATH=Contents/Code
          pytest --cov-config=.coveragerc --cov-report=xml --cov=$PYTHONPATH $PYTHONPATH/test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
